default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  # username: root
  # password: password

  username: kevin
  password: sq81816225
  host: 61.153.100.122
  port: 8888

development:
  <<: *default
  database: daisy_production

production:
  <<: *default
  database: daisy_production