elasticsearch:
  host: http://127.0.0.1:9200
  log: 'log/elasticsearch.log'
qiniu:
  ak: yRXGIzOvJBBfMOelm4O3vqasPGXj_lAuVTso4qul
  sk: ijola0yT9Gymxh7bw9ZPfQSfGZ09aHvyzWK4PRvD
  qiniu_bucket: syso
  bucket_domain: syso.qiniudn.com
  expires_in: 1576800000